### ISSUE TITLE
Reusable Flexible Layouts

### ISSUE THREAD

**Issue by ermincelikovic** [Brugman/acf-agency-workflow#13]
This might be totally out of scope or irrelevant for this plugin (please close the issue in that case), but at least it can be an idea since it kinda also elevates the agency workflow.  
  
https://support.advancedcustomfields.com/forums/topic/reusable-flexible-layouts/  
  
The idea would be actually to get to the point where flexible content layouts would act more or less like Gutenberg Blocks or even React Components - user could install a plugin which could provide custom post type, custom fields for the post type and  basic styles and template for the flexible content layout. Of course, there should be a possibility to overwrite template and styles.  
  
I know this sounds cheesy, but this could eventually lead to a little community which would share/open source the flexible layouts the same way the Gutenberg blocks are shared.

**Comment by Brugman** [comment]
Hi Ermin. The idea of plug and play components as you described them is very cool. I've heard good things about React Components but I have never used it. For AAW, this is very much out of scope. It does definitely change the "workflow", so I understand the connection, but if you'd want to create this, I would start with a blank slate, and not worry about the ACF syncing for a while.
