### ISSUE TITLE
Feature suggestion: configurable working environment

### ISSUE THREAD

**Issue by HansCz** [Brugman/acf-agency-workflow#8]
Under installation instructions you specify that

> Define `WP_ENV` as `local` on your local environment. 

Hardcoding this value might put a lot of people off. I use `development` as my standard environment name, for instance. I suspect this would vary greatly depending on who you ask.

Wouldn't it be better if this value was configurable by the user? 

Here's how I would implement it at first thought:
Create an options page accessed by a settings link in the plugin's entry in the list of installed plugins. Submitting a form on the options page would write its value to the wp_options table with a key like `acf_agency_workflow_env`.

I'll see if I can cook it up and send you a pull request.

**Comment by Brugman** [comment]
> Wouldn't it be better if this value was configurable by the user?

Completely agree!

Not sure about an "entire" options for page this, but I know you're already close to finished. I'll make a config file version to test with.

**Comment by HansCz** [comment]
I'm quite busy at the moment, so I can't finish it right now. I'll clean it up and send a pull request as soon as I have the time. Re. our last conversation, I considered the whole 'unset WP_ENV' point you made on discord. I have some comments on that, but it'll have to wait.

**Comment by Brugman** [comment]
I added it with a hook! 5d6e6b0b81914ca3058b26854591c75e0736c3cb

You can override the defaults with
```
add_filter( 'aaw_local_envs', function ( $envs ) {
    return $envs;
});
```
